GET http://localhost:3000/products

###
POST http://localhost:3000/products
content-type: application/json

{
  "name": "gloves",
  "description": "protects hands",
  "price": 10
}

###
GET http://localhost:3000/products/4

###
PATCH http://localhost:3000/products/8
content-type: application/json

{
  "name": "socks",
  "description": "warms your feet",
  "price": 7
}

###
DELETE http://localhost:3000/products/9