GET http://localhost:3000/products

###
POST http://localhost:3000/products
content-type: application/json

{
  "name": "shoes",
  "description": "protects feet",
  "price": 25,
  "supplier_id": 2 
}

###
GET http://localhost:3000/products/4

###
PATCH http://localhost:3000/products/8
content-type: application/json

{
  "name": "socks",
  "description": "warms your feet",
  "price": 7
}

###
DELETE http://localhost:3000/products/11

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Howie",
  "email": "howie@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "katrina@test.com",
  "password": "password"
}

###
POST http://localhost:3000/carted_products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDg1OTQ1NjN9.au1vRlSuEgL_GV2C0jhvSb7TdqFfFTOESM-xU22Ath4

###
GET http://localhost:3000/carted_products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1OTUxMDR9.WWP3Jy7igYo5M5wsvVjUkj-2ef_IRLzgxMFF8Zc-dXc

###
POST http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg2NTAyODB9.CC6piIs2VDA2d_o_RIjlF-ASW_MgQAdqNWogyMOfxH0

#fixed and done with orders create controller